version: "3.7"

services:
  #MTU / HMI server
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=EUROPE/London
    ports:
      - "1880:1880"
    networks:
      - SCADA-system
    volumes:
      - node-red-data:/data

  # need to add RTU / PLC elements



volumes:
  node-red-data:

networks:
  SCADA-system:
